bayes = False 
social_restraint = False # will also reward to eventually accrue back 
max_delay = 3
gifting = False
environment_used = "clean-up" # "clean-up" # "harvest"
interactive_mode = True
hpc = True
collective_reward = False
return_agent_actions = True