bayes = True 
social_restraint = False # will also reward to eventually accrue back 
max_delay = 2
gifting = False
environment_used = "harvest" # "clean-up" # "harvest"
interactive_mode = True
hpc = False
collective_reward = False
return_agent_actions = True